# -*- coding: utf-8 -*-
"""03 Lendo nomes com Json.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C3ce2PhLeFLedCXumsQVnaN8uH8_92XQ
"""

import pandas as pd

nomes_f = pd.read_json('https://guilhermeonrails.github.io/nomes_ibge/nomes-f.json')
nomes_m = pd.read_json('https://guilhermeonrails.github.io/nomes_ibge/nomes-m.json')

nomes_f

nomes_m

nomes_f.sample(5)  # este comando 'sample' ele sorteia nomes, 
#nesse exemplo ele sorteiou 5 nomes

nomes_m.sample(5) # este comando 'sample' ele sorteia nomes, 
#nesse exemplo ele sorteiou 5 nomes

print('Quantidade de nomes: ' + str(len(nomes_f) + len(nomes_m))) 
#com o comando len contamos quantas linha tem, e com o str convertemos 
#para string para podemos concatenarmos com a escrita

frames = [nomes_f, nomes_m] # juntando as duas tabelas

nomes = pd.concat(frames)['nome'] 
# concatenando a coluna nome e adicionando isso ao um novo dataframe

nomes.sample(5)